---
os: linux
dist: xenial
language: python
python:
  - 3.7
cache: pip
services:
  - docker
env:
  - ANSIBLE=2.7
  - ANSIBLE=2.8
  - ANSIBLE=2.9
install:
  - pip3 install tox-travis git-semver
script:
  - ./.travis/test.sh
branches:
  only:
    - master