---
- include: preflight.yml
  become: false
- include: install.yml
  become: true
- include: configure.yml
  become: true
- name: Enable and start service
  become: true
  systemd:
    name: hover-ddns.service
    enabled: true
    state: started
    masked: false
    daemon_reload: true
  tags: notest
